package views;

import dao.UserDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import helper.ShareHelper;
import javax.swing.JOptionPane;
import main.Main;
import model.Users;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author ACER
 */
public class ChanePassJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChanePassJDialog
     *
     * @param parent
     * @param modal
     */
    public ChanePassJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        txtEmail.setText(ShareHelper.USER.getEmailString());
        txtEmail.disable();
    }

    //chanePass
    private void chanePass() {
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtPass, sb, "Mật khẩu cũ trống hoặc không đủ 10 ký tự !");
        DataValidator.validateEmpty(txtChanePass, sb, "Mật khẩu mới trống hoặc không đủ 10 ký tự !");
        DataValidator.validateEmpty(txtChanePass1, sb, "Mật khẩu xác nhận trống hoặc không đủ 10 ký tự !");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi nhập liệu");
            return;
        }
        try {
            UserDao dao = new UserDao();
            if (!ShareHelper.USER.getPassWordString().equals(DigestUtils.md5Hex(DigestUtils.md5Hex(new String(txtPass.getPassword()))))) {
                MessageDialogHelper.showErrorDialog(this, "Mật khẩu không chính xác !", "Lỗi mật khẩu");
                DataValidator.error(txtPass, false);
            } else {
                if (!new String(txtChanePass.getPassword()).equals(new String(txtChanePass1.getPassword()))) {
                    MessageDialogHelper.showErrorDialog(this, "Xác nhận mật khẩu không chính xác !", "Lỗi mật khẩu");
                    DataValidator.error(txtChanePass, false);
                    DataValidator.error(txtChanePass1, false);
                } else {
                    Users entity = ShareHelper.USER;
                    entity.setPassWordString(DigestUtils.md5Hex(new String(txtChanePass.getPassword())));
                    try {
                        dao.update(entity);
                        MessageDialogHelper.showMessageDialog(this, "Đã cập nhập mật khẩu thành công !", "Thông báo tin nhắn");
                        dispose();
                        Main main = new Main();
                        main.setVisible(true);
                    } catch (Exception e) {
                        MessageDialogHelper.showErrorDialog(this, "Lỗi cập nhập : " + e.toString(), "Lỗi");
                        System.out.println("*ChanePassJDialog(chanePass) - " + e.toString());
                    }
                }
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi cập nhập : " + e.toString(), "Lỗi");
            System.out.println("*ChanePassJDialog(chanePass) - " + e.toString());
        }
    }

    //Exit
    private void exit() {
        if (MessageDialogHelper.showComfirmDialog(this, "Bạn có muốn thoát chương trình ?",
                "Thoát chương trình") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new swing.MyTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new swing.MyPasswordField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtChanePass = new swing.MyPasswordField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtChanePass1 = new swing.MyPasswordField();
        jPanel4 = new javax.swing.JPanel();
        btnChanePass = new swing.Button();
        btnExit = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(550, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setMaximumSize(new java.awt.Dimension(650, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 700));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel3.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jLabel2.setMaximumSize(new java.awt.Dimension(650, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(650, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(650, 100));
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(650, 470));
        jPanel5.setMinimumSize(new java.awt.Dimension(650, 470));
        jPanel5.setPreferredSize(new java.awt.Dimension(650, 470));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 12));

        jPanel6.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(650, 100));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel10.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel10.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_email_sign_25px.png"))); // NOI18N
        jLabel3.setText("Email");
        jLabel3.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel10.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setText("EMAIL");
        txtEmail.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(500, 38));
        txtEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtEmail, java.awt.BorderLayout.LINE_START);

        jPanel6.add(jPanel10);

        jPanel5.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel11.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel11.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_access_25px.png"))); // NOI18N
        jLabel4.setText("Mật khẩu cũ");
        jLabel4.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel11.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setText("myPasswordField1");
        txtPass.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtPass.setPreferredSize(new java.awt.Dimension(500, 38));
        txtPass.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel11.add(txtPass, java.awt.BorderLayout.LINE_START);

        jPanel7.add(jPanel11);

        jPanel5.add(jPanel7);

        jPanel14.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel14.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel15.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel15.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel15.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_pass_fail_25px.png"))); // NOI18N
        jLabel7.setText("Mật khẩu mới");
        jLabel7.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel15.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        txtChanePass.setBackground(new java.awt.Color(255, 255, 255));
        txtChanePass.setForeground(new java.awt.Color(0, 0, 0));
        txtChanePass.setText("myPasswordField1");
        txtChanePass.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtChanePass.setPreferredSize(new java.awt.Dimension(500, 38));
        txtChanePass.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel15.add(txtChanePass, java.awt.BorderLayout.LINE_START);

        jPanel14.add(jPanel15);

        jPanel5.add(jPanel14);

        jPanel16.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel16.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel17.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel17.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel17.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_passed_25px.png"))); // NOI18N
        jLabel8.setText("Xác nhận mật khẩu");
        jLabel8.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel17.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        txtChanePass1.setBackground(new java.awt.Color(255, 255, 255));
        txtChanePass1.setForeground(new java.awt.Color(0, 0, 0));
        txtChanePass1.setText("myPasswordField1");
        txtChanePass1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtChanePass1.setPreferredSize(new java.awt.Dimension(500, 38));
        txtChanePass1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel17.add(txtChanePass1, java.awt.BorderLayout.LINE_START);

        jPanel16.add(jPanel17);

        jPanel5.add(jPanel16);

        jPanel2.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 55, 20));

        btnChanePass.setForeground(new java.awt.Color(0, 0, 0));
        btnChanePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_submit_progress_50px.png"))); // NOI18N
        btnChanePass.setText("Xác nhận");
        btnChanePass.setEffectColor(new java.awt.Color(51, 153, 0));
        btnChanePass.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnChanePass.setMaximumSize(new java.awt.Dimension(200, 60));
        btnChanePass.setMinimumSize(new java.awt.Dimension(200, 60));
        btnChanePass.setPreferredSize(new java.awt.Dimension(200, 60));
        btnChanePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChanePassActionPerformed(evt);
            }
        });
        jPanel4.add(btnChanePass);

        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_50px.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setEffectColor(new java.awt.Color(153, 0, 51));
        btnExit.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnExit.setMaximumSize(new java.awt.Dimension(200, 60));
        btnExit.setMinimumSize(new java.awt.Dimension(200, 60));
        btnExit.setPreferredSize(new java.awt.Dimension(200, 60));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChanePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChanePassActionPerformed
        chanePass();
    }//GEN-LAST:event_btnChanePassActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChanePassJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChanePassJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChanePassJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChanePassJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChanePassJDialog dialog = new ChanePassJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnChanePass;
    private swing.Button btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private swing.MyPasswordField txtChanePass;
    private swing.MyPasswordField txtChanePass1;
    private swing.MyTextField txtEmail;
    private swing.MyPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
