package views;

/**
 *
 * @author ACER
 */
public class InfoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form InfoJDialog
     */
    public InfoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 750));
        setMinimumSize(new java.awt.Dimension(1300, 750));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 750));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jPanel7.setPreferredSize(new java.awt.Dimension(760, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("DialogInput", 2, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>Báo cáo dự án 1 của hệ Cao đẳng thực hành FPT là báo cáo sản phẩm ứng dụng desktop <br> đã được thực hiện. Báo cáo dự án 1 là yêu cầu bắt buộc đối với mỗi sinh viên khi kết thúc <br> môn dự án 1</html>");
        jPanel7.add(jLabel11, java.awt.BorderLayout.CENTER);

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel12.setText("YÊU CẦU CHUNG");
        jPanel7.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(760, 150));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("DialogInput", 2, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("<html>Hãy sử dụng report template để viết báo cáo cho dự án 1. Chú ý theo những ghi chú chỉ <br> dẫn trên tài liệu mẫu để hoàn thành. Sau khi hoàn thành thì xóa bỏ những chỉ dẫn khỏi <br> báo cáo.</html>");
        jPanel8.add(jLabel13, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel14.setText("TÀI LIỆU MẪU");
        jPanel8.add(jLabel14, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(760, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("DialogInput", 2, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("<html>Dự án 1 khuyến khích sinh viên làm độc lập, tức mỗi cá nhân thực hiện một đề tài, tuy <br> nhiên có thể thực hiện theo nhóm nhưng mỗi nhóm không quá 3 sinh viên /Đề tài</html>");
        jPanel9.add(jLabel15, java.awt.BorderLayout.CENTER);

        jLabel16.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel16.setText("HƯỚNG DẪN LÀM ĐỀ TÀI THEO NHÓM");
        jPanel9.add(jLabel16, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(760, 150));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("DialogInput", 2, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html>Danh mục đề tài được sử dụng trong dự án này: Quản lý oto</html>");
        jPanel10.add(jLabel17, java.awt.BorderLayout.CENTER);

        jLabel18.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel18.setText("DANH MỤC ĐỀ TÀI");
        jPanel10.add(jLabel18, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 750));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/avata.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/avata1.png"))); // NOI18N
        jPanel2.add(jLabel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(490, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(490, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(490, 100));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_facebook_60px.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jLabel4.setText("facebook.com/So.Lonely.1211");
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(490, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(490, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(490, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_instagram_60px.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jLabel6.setText("daivovan12");
        jPanel4.add(jLabel6);

        jPanel2.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(490, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(490, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(490, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_youtube_60px.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel5.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jLabel8.setText("channel/codecungdogstudio");
        jPanel5.add(jLabel8);

        jPanel2.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(490, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(490, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(490, 100));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_gmail_60px.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel6.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jLabel10.setText("vodai109@gmail.com");
        jPanel6.add(jLabel10);

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        setSize(new java.awt.Dimension(1300, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoJDialog dialog = new InfoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
