package views;

import chart.ModelChart;
import dao.StatisticalDao;
import helper.DatabaseHelper;
import java.awt.Color;
import java.sql.ResultSet;

/**
 *
 * @author ACER
 */
public class JfreeChartJDialog extends javax.swing.JDialog {

    private StatisticalDao dao = new StatisticalDao();

    /**
     * Creates new form JfreeChartJDialog
     */
    public JfreeChartJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        gaugeChart1();
        gaugeChart2();
        gaugeChart3();
        lineChart();
    }

    private void lineChart() {
        lineChart.addLegend("Số sản phẩm bán được", new Color(12, 84, 175), new Color(0, 108, 247));
        lineChart.addLegend("Số khách hàng trong tháng", new Color(54, 4, 143), new Color(104, 49, 200));
        lineChart.addLegend("Số hóa đơn đã xuất", new Color(5, 125, 0), new Color(95, 209, 69));
        lineChart.addLegend("Số nhân viên bán hàng", new Color(186, 37, 37), new Color(241, 100, 120));
        String string = "SELECT\n"
                + "MONTH(A.[ExportDate]) AS Thang,\n"
                + "COUNT(B.[CodeProduct]) AS SoSanPham,\n"
                + "COUNT(DISTINCT(C.[CodeCustomer])) AS SoKhachHang,\n"
                + "COUNT(DISTINCT(A.[CodeReceipt])) AS SoHoaDon,\n"
                + "COUNT(DISTINCT(A.[EmailUser])) AS SoNhanVien\n"
                + "FROM [dbo].[Receipts] A\n"
                + "JOIN [dbo].[ReceiptDetails] B ON A.[CodeReceipt] = B.[CodeRecieptDetail]\n"
                + "JOIN [dbo].[Customers] C ON C.[CodeCustomer] = A.[CodeCustormer]\n"
                + "GROUP BY MONTH(A.[ExportDate])";
//        chart.addData(new ModelChart("January", new double[]{500, 200, 80, 89}));
        try {
            ResultSet rs = DatabaseHelper.executeQuery(string);
            while (rs.next()) {
                lineChart.addData(new ModelChart("Tháng " + rs.getString("Thang"), new double[]{
                    Double.valueOf(rs.getString("SoSanPham")),
                    Double.valueOf(rs.getString("SoKhachHang")),
                    Double.valueOf(rs.getString("SoHoaDon")),
                    Double.valueOf(rs.getString("SoNhanVien"))}));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        lineChart.start();
    }

    private void gaugeChart1() {
        float totail = dao.select_totail_money();
        float totail7 = dao.select_totail_money_7();
        lbTotail.setText("Tổng tiền : " + totail + " VND");
        lbTotail7.setText("Tháng 7 : " + totail7 + " VND");
        float x = (totail7 / totail) * 100;
        gaugeChart1.setValueWithAnimation((int) x);
    }

    private void gaugeChart2() {
        float countUser = dao.select_count_user();
        lbCountUser.setText("Tổng số nhân viên : " + countUser);
        float countEmailUser = dao.select_count_email_user();
        lbCountEmailUser.setText("Số nhân viên bán hàng : " + countEmailUser);
        float x = (countEmailUser / countUser) * 100;
        gaugeChart2.setValueWithAnimation((int) x);
    }

    private void gaugeChart3() {
        float countCustomer = dao.select_count_customer();
        lbTotailCustomer.setText("Tổng số khách hàng : " + countCustomer);
        float totailCustomer = dao.select_totail_customer_7();
        lbCountCustomer.setText("Số khách hàng T7 : " + totailCustomer);
        float x = (totailCustomer / countCustomer) * 100;
        gaugeChart3.setValueWithAnimation((int) x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lineChart = new chart.LineChart();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        gaugeChart1 = new chart.GaugeChart();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbTotail7 = new javax.swing.JLabel();
        lbTotail = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        gaugeChart2 = new chart.GaugeChart();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbCountEmailUser = new javax.swing.JLabel();
        lbCountUser = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        gaugeChart3 = new chart.GaugeChart();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lbCountCustomer = new javax.swing.JLabel();
        lbTotailCustomer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THỐNG KÊ");
        setMaximumSize(new java.awt.Dimension(1800, 950));
        setMinimumSize(new java.awt.Dimension(1800, 950));
        setPreferredSize(new java.awt.Dimension(1800, 950));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(lineChart, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 250));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 240));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 240));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 240));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(240, 240));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 240));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 240));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(240, 210));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(gaugeChart1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phần trăm tổng tiền T7");
        jLabel1.setPreferredSize(new java.awt.Dimension(240, 30));
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setMaximumSize(new java.awt.Dimension(260, 240));
        jPanel5.setMinimumSize(new java.awt.Dimension(260, 240));
        jPanel5.setPreferredSize(new java.awt.Dimension(260, 240));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 75));

        lbTotail7.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbTotail7.setForeground(new java.awt.Color(102, 102, 102));
        lbTotail7.setText("Tháng 7 : 200 VND");
        lbTotail7.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel5.add(lbTotail7);

        lbTotail.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbTotail.setForeground(new java.awt.Color(102, 102, 102));
        lbTotail.setText("Tổng tiền : 200 VND");
        lbTotail.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel5.add(lbTotail);

        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel3);

        jPanel7.setMaximumSize(new java.awt.Dimension(500, 240));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(240, 240));
        jPanel8.setMinimumSize(new java.awt.Dimension(240, 240));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(240, 210));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(gaugeChart2, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jLabel5.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phần trăm nhân viên bán hàng");
        jLabel5.setPreferredSize(new java.awt.Dimension(240, 30));
        jPanel8.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel10.setMaximumSize(new java.awt.Dimension(260, 240));
        jPanel10.setMinimumSize(new java.awt.Dimension(260, 240));
        jPanel10.setPreferredSize(new java.awt.Dimension(260, 240));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 75));

        lbCountEmailUser.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbCountEmailUser.setForeground(new java.awt.Color(102, 102, 102));
        lbCountEmailUser.setText("Số nhân viên bán hàng : 10");
        lbCountEmailUser.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel10.add(lbCountEmailUser);

        lbCountUser.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbCountUser.setForeground(new java.awt.Color(102, 102, 102));
        lbCountUser.setText("Tổng số nhân viên : 20");
        lbCountUser.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel10.add(lbCountUser);

        jPanel7.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel7);

        jPanel11.setMaximumSize(new java.awt.Dimension(500, 240));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setMaximumSize(new java.awt.Dimension(240, 240));
        jPanel12.setMinimumSize(new java.awt.Dimension(240, 240));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(240, 210));
        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel13.add(gaugeChart3, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jLabel9.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Phần trăm khách hàng trong T7");
        jLabel9.setPreferredSize(new java.awt.Dimension(240, 30));
        jPanel12.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel14.setMaximumSize(new java.awt.Dimension(260, 240));
        jPanel14.setMinimumSize(new java.awt.Dimension(260, 240));
        jPanel14.setPreferredSize(new java.awt.Dimension(260, 240));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 75));

        lbCountCustomer.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbCountCustomer.setForeground(new java.awt.Color(102, 102, 102));
        lbCountCustomer.setText("Số khách hàng T7 : 10");
        lbCountCustomer.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel14.add(lbCountCustomer);

        lbTotailCustomer.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbTotailCustomer.setForeground(new java.awt.Color(102, 102, 102));
        lbTotailCustomer.setText("Tổng số khách hàng : 20");
        lbTotailCustomer.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel14.add(lbTotailCustomer);

        jPanel11.add(jPanel14, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel11);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfreeChartJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfreeChartJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfreeChartJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfreeChartJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JfreeChartJDialog dialog = new JfreeChartJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chart.GaugeChart gaugeChart1;
    private chart.GaugeChart gaugeChart2;
    private chart.GaugeChart gaugeChart3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbCountCustomer;
    private javax.swing.JLabel lbCountEmailUser;
    private javax.swing.JLabel lbCountUser;
    private javax.swing.JLabel lbTotail;
    private javax.swing.JLabel lbTotail7;
    private javax.swing.JLabel lbTotailCustomer;
    private chart.LineChart lineChart;
    // End of variables declaration//GEN-END:variables
}
