package views;

import dao.UserDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import helper.ShareHelper;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Users;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author ACER
 */
public class LoginJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginJDialog
     *
     * @param parent
     * @param modal
     */
    public LoginJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //Exit
    private void exit() {
        if (MessageDialogHelper.showComfirmDialog(this, "Bạn có muốn thoát chương trình ?",
                "Thoát chương trình") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    //Login
    private void login() {
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmail(txtEmail, sb, "Email trống hoặc không đúng định dạng !");
        DataValidator.validateEmpty(txtPass, sb, "Mật khẩu trống hoặc không đủ 10 ký tự !");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi nhập liệu");
            return;
        }
        boolean pos = true;
        if (rbtEmloye.isSelected()) {
            pos = false;
        }
        try {
            UserDao dao = new UserDao();
            Users entity = dao.select_By_PK(txtEmail.getText().trim());
            if (entity == null) {
                MessageDialogHelper.showErrorDialog(this, "Email không chính xác !", "Lỗi email");
                DataValidator.error(txtEmail, false);
            } else {
                if (!entity.getPassWordString().equals(DigestUtils.md5Hex(DigestUtils.md5Hex(new String(txtPass.getPassword()))))) {
                    MessageDialogHelper.showErrorDialog(this, "Mật khẩu không chính xác !", "Lỗi mật khẩu");
                    DataValidator.error(txtPass, false);
                } else {
                    if (entity.getPositionBoolean() != pos) {
                        MessageDialogHelper.showErrorDialog(this, "Vai trò không chính xác !", "Lỗi vai trò");
                    } else {
                        ShareHelper.USER = entity;
                        MessageDialogHelper.showMessageDialog(this, "Xin chào - " + entity.getEmailString(), "Thông báo tin nhắn");
                        this.dispose();
                    }
                }
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi đăng nhập : " + e.toString(), "Lỗi");
            System.out.println("*LoginJDialog(login) - " + e.toString());
        }
    }

    //register
    private void register() {
        dispose();
        new RegisterJDialog(new JFrame(), true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new swing.MyTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new swing.MyPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        rbtMana = new swing.RadioButtonCustom();
        rbtEmloye = new swing.RadioButtonCustom();
        jPanel9 = new javax.swing.JPanel();
        jLbRegister = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLogin = new swing.Button();
        btnExit = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(550, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setMaximumSize(new java.awt.Dimension(650, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 700));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel3.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        jLabel2.setMaximumSize(new java.awt.Dimension(650, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(650, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(650, 100));
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(650, 470));
        jPanel5.setMinimumSize(new java.awt.Dimension(650, 470));
        jPanel5.setPreferredSize(new java.awt.Dimension(650, 470));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 12));

        jPanel6.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(650, 100));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel10.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel10.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_email_sign_25px.png"))); // NOI18N
        jLabel3.setText("Email");
        jLabel3.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel10.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setText("dangndpd03607@fpt.edu.vn");
        txtEmail.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(500, 45));
        txtEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel10.add(txtEmail, java.awt.BorderLayout.LINE_START);

        jPanel6.add(jPanel10);

        jPanel5.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel11.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel11.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_access_25px.png"))); // NOI18N
        jLabel4.setText("Mật khẩu");
        jLabel4.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel11.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setText("12345678910");
        txtPass.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        txtPass.setPreferredSize(new java.awt.Dimension(500, 45));
        txtPass.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel11.add(txtPass, java.awt.BorderLayout.LINE_START);

        jPanel7.add(jPanel11);

        jPanel5.add(jPanel7);

        jPanel8.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel8.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jPanel12.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel12.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel12.setPreferredSize(new java.awt.Dimension(500, 80));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_people_25px.png"))); // NOI18N
        jLabel5.setText("Vai trò");
        jLabel5.setMaximumSize(new java.awt.Dimension(34, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(34, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel12.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        buttonGroup1.add(rbtMana);
        rbtMana.setForeground(new java.awt.Color(0, 0, 0));
        rbtMana.setSelected(true);
        rbtMana.setText("Trưởng phòng");
        rbtMana.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jPanel13.add(rbtMana);

        rbtEmloye.setBackground(new java.awt.Color(153, 153, 0));
        buttonGroup1.add(rbtEmloye);
        rbtEmloye.setForeground(new java.awt.Color(0, 0, 0));
        rbtEmloye.setText("Nhân viên");
        rbtEmloye.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jPanel13.add(rbtEmloye);

        jPanel12.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel12);

        jPanel5.add(jPanel8);

        jPanel9.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel9.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLbRegister.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jLbRegister.setForeground(new java.awt.Color(0, 0, 204));
        jLbRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbRegister.setText("Chưa có tài khoản ?");
        jLbRegister.setMaximumSize(new java.awt.Dimension(650, 100));
        jLbRegister.setMinimumSize(new java.awt.Dimension(650, 100));
        jLbRegister.setPreferredSize(new java.awt.Dimension(650, 100));
        jLbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbRegisterMouseExited(evt);
            }
        });
        jPanel9.add(jLbRegister, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        jPanel2.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(650, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(650, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 55, 20));

        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_login_50px.png"))); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.setEffectColor(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnLogin.setPreferredSize(new java.awt.Dimension(200, 60));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin);

        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_50px.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setEffectColor(new java.awt.Color(153, 0, 51));
        btnExit.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnExit.setPreferredSize(new java.awt.Dimension(200, 60));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLbRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbRegisterMouseClicked
        register();
    }//GEN-LAST:event_jLbRegisterMouseClicked

    private void jLbRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbRegisterMouseEntered
        jLbRegister.setForeground(Color.red);
    }//GEN-LAST:event_jLbRegisterMouseEntered

    private void jLbRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbRegisterMouseExited
        jLbRegister.setForeground(new Color(0, 0, 204));
    }//GEN-LAST:event_jLbRegisterMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginJDialog dialog = new LoginJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnExit;
    private swing.Button btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private swing.RadioButtonCustom rbtEmloye;
    private swing.RadioButtonCustom rbtMana;
    private swing.MyTextField txtEmail;
    private swing.MyPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
