package views;

import dao.StatisticalDao;
import helper.MessageDialogHelper;
import helper.ShareHelper;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class ManagerReceiptJDialog extends javax.swing.JDialog {

    private StatisticalDao daoStatisticalDao = new StatisticalDao();
    private List<Object[]> list = daoStatisticalDao.select_receipt("All");

    /**
     * Creates new form ManagerReceiptJDialog
     *
     * @param parent
     * @param modal
     */
    public ManagerReceiptJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        setIconImage(ShareHelper.APP_ICON);
        tableReciept.fixTable(jScrollPane2);
        fillTable(list);
        fillComboBoxMoney();
        fillComboBoxAmount();
        fillComboBoxDate();
    }

    //Load dữ liệu cbx
    private void fillComboBoxMoney() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxMoney.getModel();
        model.removeAllElements();
        try {
            model.addElement("--All--");
            model.addElement("Cao nhất");
            model.addElement("Thấp nhất");
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi load cbx : " + e.toString(), "Lỗi");
            System.out.println("*ManagerReceiptJDialog(fillComboBoxMoney) - " + e.toString());
        }
    }

    private void fillComboBoxDate() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxDate.getModel();
        model.removeAllElements();
        try {
            model.addElement("--All--");
            model.addElement("Gần nhất");
            model.addElement("Xa nhất");
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi load cbx : " + e.toString(), "Lỗi");
            System.out.println("*ManagerReceiptJDialog(fillComboBoxDate) - " + e.toString());
        }
    }

    private void fillComboBoxAmount() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxAmount.getModel();
        model.removeAllElements();
        try {
            model.addElement("--All--");
            model.addElement("Tăng dần");
            model.addElement("Giảm dần");
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi load cbx : " + e.toString(), "Lỗi");
            System.out.println("*ManagerReceiptJDialog(fillComboBoxAmount) - " + e.toString());
        }
    }

    //load all data
    private void fillTable(List<Object[]> list) {
        try {
            DefaultTableModel model = (DefaultTableModel) tableReciept.getModel();
            model.setRowCount(0);
            for (Object[] object : list) {
                model.addRow(object);
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi dữ liệu bảng : " + e.toString(), "Lỗi");
            System.out.println("*ManagerReceiptJDialog(fillTable) - " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReciept = new swing.TableDark();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxMoney = new swing.ComboBoxSuggestion();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxAmount = new swing.ComboBoxSuggestion();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxDate = new swing.ComboBoxSuggestion();
        btnSearch = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ HÓA ĐƠN");
        setMaximumSize(new java.awt.Dimension(1800, 950));
        setMinimumSize(new java.awt.Dimension(1800, 950));
        setPreferredSize(new java.awt.Dimension(1800, 950));

        jPanel1.setLayout(new java.awt.BorderLayout());

        tableReciept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nhân viên", "Tên khách hàng", "Ngày suất", "Số sản phẩm", "Giảm giá ( % -> VND)", "Thuế ( VND )", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReciept.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        tableReciept.setRowHeight(50);
        tableReciept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRecieptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableReciept);
        if (tableReciept.getColumnModel().getColumnCount() > 0) {
            tableReciept.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 80));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("XẮP SẾP");
        jPanel2.add(jLabel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setText("Tổng tiền:");
        jPanel3.add(jLabel2);

        cbxMoney.setForeground(new java.awt.Color(51, 51, 51));
        cbxMoney.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMoney.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        cbxMoney.setPreferredSize(new java.awt.Dimension(150, 50));
        cbxMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMoneyActionPerformed(evt);
            }
        });
        jPanel3.add(cbxMoney);

        jPanel2.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel3.setText("Số lượng:");
        jPanel4.add(jLabel3);

        cbxAmount.setForeground(new java.awt.Color(51, 51, 51));
        cbxAmount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAmount.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        cbxAmount.setPreferredSize(new java.awt.Dimension(150, 50));
        cbxAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAmountActionPerformed(evt);
            }
        });
        jPanel4.add(cbxAmount);

        jPanel2.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setText("Ngày xuất:");
        jPanel5.add(jLabel4);

        cbxDate.setForeground(new java.awt.Color(51, 51, 51));
        cbxDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxDate.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        cbxDate.setPreferredSize(new java.awt.Dimension(150, 50));
        cbxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDateActionPerformed(evt);
            }
        });
        jPanel5.add(cbxDate);

        jPanel2.add(jPanel5);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_40px.png"))); // NOI18N
        btnSearch.setEffectColor(new java.awt.Color(0, 153, 204));
        btnSearch.setMaximumSize(new java.awt.Dimension(40, 40));
        btnSearch.setMinimumSize(new java.awt.Dimension(40, 40));
        btnSearch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableRecieptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRecieptMouseClicked
        int row = tableReciept.getSelectedRow();
        String code = (String) tableReciept.getValueAt(row, 0);
        new ManagerReceiptDetailJDialog(new JFrame(), true, code).setVisible(true);
    }//GEN-LAST:event_tableRecieptMouseClicked

    private void cbxMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMoneyActionPerformed
        if (!String.valueOf(cbxMoney.getSelectedItem()).equals("--All--")) {
            cbxDate.setSelectedItem("--All--");
            cbxAmount.setSelectedItem("--All--");
        }
    }//GEN-LAST:event_cbxMoneyActionPerformed

    private void cbxAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAmountActionPerformed
        if (!String.valueOf(cbxAmount.getSelectedItem()).equals("--All--")) {
            cbxDate.setSelectedItem("--All--");
            cbxMoney.setSelectedItem("--All--");
        }
    }//GEN-LAST:event_cbxAmountActionPerformed

    private void cbxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDateActionPerformed
        if (!String.valueOf(cbxDate.getSelectedItem()).equals("--All--")) {
            cbxMoney.setSelectedItem("--All--");
            cbxAmount.setSelectedItem("--All--");
        }
    }//GEN-LAST:event_cbxDateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String money = (String) cbxMoney.getSelectedItem();
        String amount = (String) cbxAmount.getSelectedItem();
        String date = (String) cbxDate.getSelectedItem();
        if (!money.equals("--All--")) {
            if (money.equals("Cao nhất")) {
                fillTable(daoStatisticalDao.select_receipt("MoneyDESC"));
            } else if (money.equals("Thấp nhất")) {
                fillTable(daoStatisticalDao.select_receipt("MoneyASC"));
            }
        }
        if (!amount.equals("--All--")) {
            if (amount.equals("Giảm dần")) {
                fillTable(daoStatisticalDao.select_receipt("AmountDESC"));
            } else if (amount.equals("Tăng dần")) {
                fillTable(daoStatisticalDao.select_receipt("AmountASC"));
            }
        }
        if (!date.equals("--All--")) {
            if (date.equals("Gần nhất")) {
                fillTable(daoStatisticalDao.select_receipt("DateDESC"));
            } else if (date.equals("Xa nhất")) {
                fillTable(daoStatisticalDao.select_receipt("DateASC"));
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagerReceiptJDialog dialog = new ManagerReceiptJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnSearch;
    private swing.ComboBoxSuggestion cbxAmount;
    private swing.ComboBoxSuggestion cbxDate;
    private swing.ComboBoxSuggestion cbxMoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.TableDark tableReciept;
    // End of variables declaration//GEN-END:variables
}
