package views;

import dao.CustomerDao;
import dao.ReceiptDao;
import dao.StatisticalDao;
import helper.MessageDialogHelper;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Customers;
import model.Receipts;

/**
 *
 * @author ACER
 */
public class ManagerReceiptDetailJDialog extends javax.swing.JDialog {
    
    private String code;
    private ReceiptDao daoReceipt = new ReceiptDao();
    private CustomerDao daoCustomer = new CustomerDao();
    private StatisticalDao daoStatistical = new StatisticalDao();

    /**
     * Creates new form ManagerReceiptDetailJDialog
     */
    public ManagerReceiptDetailJDialog(java.awt.Frame parent, boolean modal, String code) {
        super(parent, modal);
        this.code = code;
//        tableCardetail.fixTable(jScrollPane1);
        initComponents();
        fillInfo();
        fillTable();
    }
    
    private ManagerReceiptDetailJDialog(JFrame jFrame, boolean b) {
    }
    
    private void fillInfo() {
        Receipts receipts = daoReceipt.select_By_PK(code);
        Customers customers = daoCustomer.select_By_PK(receipts.getCodeCustormerString());
        jlbCodeReceipt.setText("Mã hóa đơn : " + code);
        jlbCodeCustomer.setText("Mã khách hàng : " + customers.getCodeCustomerString());
        jlbUserName.setText("Họ và tên : " + customers.getNameString());
        jlbEmail.setText("Email : " + customers.getEmailString());
        jlbPhone.setText("Số điện thoại : " + customers.getPhoneString());
        jlbAddress.setText("Địa chỉ : " + customers.getAddressString());
        String sex = customers.getSexBoolean() ? "Nam" : "Nữ";
        jlbSex.setText("Giới tính : " + sex);
        jlbBrithDay.setText("Ngày sinh : " + customers.getBirthDayDate());
        for (Object[] object : daoStatistical.select_receipt_detail_money(code)) {
            jlbTotail.setText("Tổng tiền sản phẩm : " + object[0] + "VND");
            jlbDiscount.setText("Giảm giá " + "(" + object[1] + "%):" + object[2] + "VND");
            jlbVAT.setText("Thuế VAT " + "(" + object[3] + "%):" + object[4] + "VND");
            jlbTotailMoney.setText("Tổng tiền : " + object[5] + " VND");
        }
    }

    //load all data
    private void fillTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tableCardetail.getModel();
            model.setRowCount(0);
            for (Object[] object : daoStatistical.select_receipt_detail(code)) {
                model.addRow(object);
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi dữ liệu bảng : " + e.toString(), "Lỗi");
            System.out.println("*ManagerReceiptDetailJDialog(fillTable) - " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCardetail = new swing.TableDark();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlbCodeReceipt = new javax.swing.JLabel();
        jlbCodeCustomer = new javax.swing.JLabel();
        jlbUserName = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jlbPhone = new javax.swing.JLabel();
        jlbAddress = new javax.swing.JLabel();
        jlbSex = new javax.swing.JLabel();
        jlbBrithDay = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbTotail = new javax.swing.JLabel();
        jlbDiscount = new javax.swing.JLabel();
        jlbVAT = new javax.swing.JLabel();
        jlbTotailMoney = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HÓA ĐƠN CHI TIẾT");
        setMinimumSize(new java.awt.Dimension(1220, 820));
        setPreferredSize(new java.awt.Dimension(1220, 820));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tableCardetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCardetail.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        tableCardetail.setRowHeight(50);
        jScrollPane1.setViewportView(tableCardetail);
        if (tableCardetail.getColumnModel().getColumnCount() > 0) {
            tableCardetail.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(0, 220));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        jPanel6.setPreferredSize(new java.awt.Dimension(585, 200));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jlbCodeReceipt.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbCodeReceipt.setText("Mã hóa đơn : MÃ HÓA ĐƠN");
        jlbCodeReceipt.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbCodeReceipt.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbCodeReceipt.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel6.add(jlbCodeReceipt);

        jlbCodeCustomer.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbCodeCustomer.setText("Mã khách hàng : MÃ KHÁCH HÀNG");
        jlbCodeCustomer.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbCodeCustomer.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbCodeCustomer.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel6.add(jlbCodeCustomer);

        jlbUserName.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbUserName.setText("Họ và tên : HỌ VÀ TÊN");
        jlbUserName.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbUserName.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbUserName.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel6.add(jlbUserName);

        jlbEmail.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbEmail.setText("Email : EMAIL");
        jlbEmail.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbEmail.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbEmail.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel6.add(jlbEmail);

        jPanel4.add(jPanel6);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jlbPhone.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbPhone.setText("Số điện thoại : SỐ ĐIỆN THOẠI");
        jlbPhone.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbPhone.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbPhone.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel8.add(jlbPhone);

        jlbAddress.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbAddress.setText("Địa chỉ : ĐỊA CHỈ");
        jlbAddress.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbAddress.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbAddress.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel8.add(jlbAddress);

        jlbSex.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbSex.setText("Giới tính : GIỚI TÍNH");
        jlbSex.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbSex.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbSex.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel8.add(jlbSex);

        jlbBrithDay.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbBrithDay.setText("Ngày sinh : NGÀY SINH");
        jlbBrithDay.setMaximumSize(new java.awt.Dimension(585, 50));
        jlbBrithDay.setMinimumSize(new java.awt.Dimension(585, 50));
        jlbBrithDay.setPreferredSize(new java.awt.Dimension(585, 50));
        jPanel8.add(jlbBrithDay);

        jPanel4.add(jPanel8);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 200));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jlbTotail.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbTotail.setText("Tổng tiền sản phẩm : 1.000.000.000.000 VND");
        jlbTotail.setMaximumSize(new java.awt.Dimension(500, 50));
        jlbTotail.setMinimumSize(new java.awt.Dimension(500, 50));
        jlbTotail.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.add(jlbTotail);

        jlbDiscount.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbDiscount.setText("Giảm giá (2%) : 50.000.000 VND");
        jlbDiscount.setMaximumSize(new java.awt.Dimension(500, 50));
        jlbDiscount.setMinimumSize(new java.awt.Dimension(500, 50));
        jlbDiscount.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.add(jlbDiscount);

        jlbVAT.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        jlbVAT.setText("Thuế VAT (20%) : 30.000.000 VND");
        jlbVAT.setMaximumSize(new java.awt.Dimension(500, 50));
        jlbVAT.setMinimumSize(new java.awt.Dimension(500, 50));
        jlbVAT.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.add(jlbVAT);

        jlbTotailMoney.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jlbTotailMoney.setForeground(new java.awt.Color(153, 0, 0));
        jlbTotailMoney.setText("Tổng tiền : 500.000.000 VND");
        jlbTotailMoney.setMaximumSize(new java.awt.Dimension(500, 50));
        jlbTotailMoney.setMinimumSize(new java.awt.Dimension(500, 50));
        jlbTotailMoney.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.add(jlbTotailMoney);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HÓA ĐƠN THANH TOÁN");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 80));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerReceiptDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagerReceiptDetailJDialog dialog = new ManagerReceiptDetailJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbAddress;
    private javax.swing.JLabel jlbBrithDay;
    private javax.swing.JLabel jlbCodeCustomer;
    private javax.swing.JLabel jlbCodeReceipt;
    private javax.swing.JLabel jlbDiscount;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbPhone;
    private javax.swing.JLabel jlbSex;
    private javax.swing.JLabel jlbTotail;
    private javax.swing.JLabel jlbTotailMoney;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JLabel jlbVAT;
    private swing.TableDark tableCardetail;
    // End of variables declaration//GEN-END:variables
}
